# Generated by Django 3.0.2 on 2020-01-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('txt1', models.CharField(max_length=50)),
                ('txt2', models.CharField(max_length=50)),
                ('txt3', models.CharField(max_length=50)),
            ],
        ),
    ]
