# Generated by Django 3.0.2 on 2020-01-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('slug', models.CharField(max_length=70)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
