# Generated by Django 3.0.2 on 2020-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_posts_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='thumb',
            field=models.ImageField(default=False, upload_to='static/img/'),
        ),
    ]
