# Generated by Django 3.0.2 on 2020-01-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200129_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='thumb',
            field=models.ImageField(default=False, upload_to='media/'),
        ),
    ]
